### ISSUE TITLE
Fix or remove Hula.

### ISSUE THREAD

**Issue by robertsoule-barefoot** [p4lang/tutorials#105]

**Comment by kevinbird61** [comment]
Sorry, I'm new to P4, and when I was practicing with exercise - under folder: SIGCOMM_2017/exercises/hula
And I found after I follow the guide to construct hula.p4, it still can't let h1 ping h2.

Is that why this issue(fix or remove) exists? 

And I found 

Thanks.

**Comment by alex1230608** [comment]
After tracing the code, I wanted to ask a question about this, too!

Based on my understanding of the header stack's `pop_front` function, I think `srcRoute_nhop()` will remove the first entry in `srcRoutes`. Therefore, after a probe has been received by the destination switch (along the forward path), there will be no more `srcRoutes` entries left in the header, so during the backward path, we cannot use `srcRoutes to send the probes back to the source switch.

Am I right? If this is really a bug, what's the suggestion to fix it?
Should we use two header stacks, one for forward path and the other for backward path?
Or, to avoid the overhead, is it possible to use the following instead?
```
    // the srcRoutes are in a reverse order, and 
    // hopCount is initialized to the length of the stack minus one
    action srcRoute_forward_nhop() {
        standard_metadata.egress_spec = (bit<9>)hdr.srcRoutes[hdr.hula.hopCount].port;
        hdr.hula.hopCount = hdr.hula.hopCount - 1;
    }
    action srcRoute_backward_nhop() {
        standard_metadata.egress_spec = (bit<9>)hdr.srcRoutes[0].port;
        hdr.srcRoutes.pop_front(1);
    }
```

**Comment by jnfoster** [comment]
To answer the question, the sender of the probe puts both the forward path and the backward path in the header stack. So the destination just needs to remove the entry and follow the port in the next header.

The functionality in this code is correct, and we have confirmed that `ping` still works using the VM from August.

However it has bit rotted against the main p4c and bmv2 software repositories, largely due to changes to p4c and `v1model.p4`. It was not used in the November Developer Day, which was based on the P4 App Docker container rather than a VM. The GitHub issue is a note about this.

We may resurrect this for the next Developer Day in May but it's low priority for us. You should feel free to create a PR with updates for the current software versions.

**Comment by masoudmj** [comment]
@alex1230608 
I think with the current implementation the proposed modification doesn't work.
This is because the sender assumed that the destination uses the ingress port and doesn't remove an entry from the hop stack here:
https://github.com/p4lang/tutorials/blob/master/SIGCOMM_2017/exercises/hula/generatehula.py#L46

If you want the destination to use the value in stack instead of the ingress port, please change the the generatehula.py to insert the port in the stack too. However, I don't see any benefit.

**Comment by alex1230608** [comment]
Oh~ I see. It's because I ran it on a different environment, so I used a different program to send the probes. Sorry for confusing and thank you, both!
