### ISSUE TITLE
For MRI, include the IP options in the IP checksum.

### ISSUE THREAD

**Issue by robertsoule-barefoot** [p4lang/tutorials#106]
Need to check how to modify the checksum function to take in header stacks as input.

**Comment by NofelYaseen** [comment]
Here are few ideas:
1. When computing checksum, check each header stack index exists and update the checksum.
2. Change the design of mri. Rather than having a stack, add a fixed size header, something like:
```
header mri_t {
    bit<16>  count;
    switchID_t  swid1;
    qdepth_t    qdepth1;
    switchID_t  swid2;
    qdepth_t    qdepth2;
    switchID_t  swid2;
    qdepth_t    qdepth2;
}
```
3. If the end goal is to process some header within the network only, you can remove the header before forwarding to the host.
