### ISSUE TITLE
Some problem occur when I reinstall P4

### ISSUE THREAD

**Issue by kevinbird61** [p4lang/tutorials#113]
![image](https://user-images.githubusercontent.com/6426812/35713989-373daa3a-0805-11e8-874c-814854ff2dd1.png)

When I reinstall p4c on my pc, after I install all dependencies, I found those error message when I run example with solution code. ( `Invalid table name` )

Does this problem in my `p4c` or `bmv2`?

Thank you!

P.S. First time I install P4 with p4c, bmv2 doesn't occur these problems. (About 1~2 months ago)

**Comment by jnfoster** [comment]
Hmm. I'm not sure, but from the error message, it looks like this is unrelated to the version of `p4c` or `bmv2` you have installed. It seems likely that the script that reads the table commands files is attempting to install rules in a table that does not actually exist (`ipv4_lpm`) and so `bmv2` is printing an error.

If you provided some additional information like: 
* what command did you run, 
* what version of the tutorials repository did you have checked out from GitHub, 
* what directory did you run it from, 
* what other files were in that directory, what output did the compiler produce, etc. 

I might be able to help. But without at least some of that, it's pretty difficult. And formatting the output in Markdown instead of uploading a screenshot is always appreciated -- it makes it easier to search, cut and paste, etc. Here's a note on [asking questions](http://www.cs.cornell.edu/courses/cs3110/2018sp/thoughtful.html) I share with my undergrads.

**Comment by kevinbird61** [comment]
Sorry about asking problem without mention any details.

Here is the information:
* The repository I used (The latest version of tutorials):
    * [p4lang/tutorials/SIGCOMM2017/basic](https://github.com/p4lang/tutorials/tree/master/SIGCOMM_2017/exercises/basic)
* The command I run: `sudo ./run.sh`
* The output file: `basic.p4.json` (quite long) :
```js
... 
"pipelines" : [
    {
      "name" : "ingress",
      "id" : 0,
      "source_info" : {
        "filename" : "basic.p4",
        "line" : 86,
        "column" : 8,
        "source_fragment" : "MyIngress"
      },
      "init_table" : "node_2",
      "tables" : [
        {
          "name" : "MyIngress.ipv4_lpm",
          "id" : 0,
          "source_info" : {
            "filename" : "basic.p4",
            "line" : 100,
            "column" : 10,
            "source_fragment" : "ipv4_lpm"
          },
          "key" : [
            {
              "match_type" : "lpm",
              "name" : "hdr.ipv4.dstAddr",
              "target" : ["ipv4", "dstAddr"],
              "mask" : null
            },
...
            "actions" : ["MyIngress.ipv4_forward", "MyIngress.drop", "NoAction"],
```

Here is see there existed a table named `MyIngress.ipv4_lpm` in pipelines ( name: `ingress` ) , which all the action have a table name as prefix.

And I found the older version ( `p4c`  in `master`, commit  [80fa9ae](https://github.com/p4lang/p4c/commit/80fa9aec25c7da6600690439363072b5e946f495)  ) generated one is a table named `ipv4_lpm`, without the control block name.
* The older version one:
```js
...
"pipelines" : [
    {
      "name" : "ingress",
      "id" : 0,
      "source_info" : {
        "filename" : "basic.p4",
        "line" : 91,
        "column" : 8,
        "source_fragment" : "MyIngress"
      },
      "init_table" : "node_2",
      "tables" : [
        {
          "name" : "ipv4_lpm",
          "id" : 0,
          "source_info" : {
            "filename" : "basic.p4",
            "line" : 109,
            "column" : 10,
            "source_fragment" : "ipv4_lpm"
          },
          "key" : [
            {
              "match_type" : "lpm",
              "target" : ["ipv4", "dstAddr"],
              "mask" : null
            },
...
          "actions" : ["ipv4_forward", "drop", "NoAction"],
```

And I found the actions name in older one are without name of control block.

I supposed this is the different behavior of `p4c`?

---

Thanks for your help and correction about asking problem !

**Comment by jafingerhut** [comment]
There was a recent change made to p4c when compiling P4_16 source code that causes it to use hierarchical names for tables and externs inside of control blocks like ingress and egress, since P4_16 allows tables with the same names to be used inside of each.

I think that this may have changed the names required to be used via simple_switch_CLI, or perhaps any other control planes that control simple_switch via Thrift.

@antoninbas Does this sound like it might be a correct analysis?  I know you and perhaps others made changes to some methods of controlling simple_switch so that the full hierarchical name was unnecessary if the table / extern names were otherwise unique, by default.  Might those changes apply only for non-Thrift methods of sending control updates to simple_switch?

**Comment by antoninbas** [comment]
@jafingerhut you are correct, what @kevinbird61 is due to https://github.com/p4lang/p4c/pull/1106
P4 Runtime is mostly unaffected because it uses ids instead of names, although clients which rely on P4Info to map names to ids usually need to be updated.
I will update simple_switch_CLI so that it accepts unique suffixes as valid identifiers. However, I will not update the Thrift server itself so if there are some clients which use the Thrift server directly with P4_16 programs (I doubt there are too many), they will need to be updated to use fully-qualified names.
The tutorials repo only uses simple_switch_CLI so once I update it to accept unique suffixes, P4_16 examples should not be broken any more.

**Comment by antoninbas** [comment]
I updated the bmv2 CLI to support unique suffixes: https://github.com/p4lang/behavioral-model/pull/544
However, I would recommend using the fully-qualified names in future exercises (for future P4D2 events).

On a related note, the p4runtime exercise (https://github.com/p4lang/tutorials/tree/master/P4D2_2017_Fall/exercises/p4runtime) will not work with recent versions of p4c / bmv2 / P4Runtime. I have a patch for it but I'm reluctant to apply it since if I did the exercise would no longer work for the repositories' shas used in the vagrant scripts. I suppose I could update these as well...

**Comment by jnfoster** [comment]
Antonin, we are finalizing a new version of the VM and tutorials. Does it make sense to now apply that second patch?

**Comment by antoninbas** [comment]
It seems that Rob applied my patch in his PR (https://github.com/p4lang/tutorials/pull/116) which adds a folder for the upcoming D2 day. I personally believe creating a new folder for each event and freezing it after the event is the right approach - which means that people interested in going through the tutorial after the event need to make sure that they are using the VM or that they have the correct versions of the dependencies installed.
