### ISSUE TITLE
Why not increase the 'totalLen' field in IP header?

### ISSUE THREAD

**Issue by VerricDr** [p4lang/tutorials#140]
Hi all, 
    I am learning MRI example. When switch adds meta info(switch id and queue depth) to a packet, why not modify 'totalLen' in IP header?
When I use Wireshark analysis captured file, the length is always a specific length. Thanks.

**Comment by jafingerhut** [comment]
A guess (sorry, I have not gone through the MRI example in detail): When creating a demo P4 program for tutorial purposes, getting all of the details exactly right that one might need in a production-quality P4 program can distract people learning the language for the first time.  This is the same phenomenon when teaching any programming language for the first time -- one typically leaves out details that production-quality programs typically have, in order to focus on the essentials.

**Comment by jnfoster** [comment]
@jafingerhut is exactly right.
