### ISSUE TITLE
Error when requesting config md5 sum from switch

### ISSUE THREAD

**Issue by faizatahir94** [p4lang/tutorials#17]
In the meter , while running the command " ./run_switch.sh " it shows up the error  " Error when requesting config md5 sum from switch" the thirft server is running properly and displays the message READY. While I am running my python file using command " sudo python send_and_receive.py 1", I am not getting the desired output. Instead of sending two packet it is sending just one packets. Moreover when I change the veth pairs the output the output changes to two receive packets and one send packets. Can any one help in figuring out where the problem lies. 
![screenshot from 2017-02-10 00-58-44](https://cloud.githubusercontent.com/assets/24804568/22820899/926d0c4e-ef2d-11e6-8e07-d577890c326a.png)
![screenshot from 2017-02-10 01-00-28](https://cloud.githubusercontent.com/assets/24804568/22820913/a3824e90-ef2d-11e6-9806-985f17e8faca.png)

**Comment by antoninbas** [comment]
The switch didn't start, which is why the CLI was not able to connect to it in order to retrieve the md5 checksum.
There are a few things you could try. You could try adding `--log-console` to the switch command in `run_switch.sh` and look for error messages.
You could also try starting the switch yourself with `sudo $SWITCH_PATH meter.json --log-console` and then try starting the CLI in a separate terminal.
I'm guessing this could happen if you have a version mismatch between the thrift compiler version and the thrift python package, so you could check that as well.

**Comment by faizatahir94** [comment]
using " ./ run_switch.sh --log-console " is not displaying any difference in the output. I am getting the same output as in the screen shot above. I have tested my behavioral model with thrift versions 0.9.2, 0.9.3, 0.10.0 and 1.0.0 separately. When i run my meter example, I am still getting this error. Any idea if i have to run my code with out run_switch.sh, who will i populate my tables from commands.txt file?

**Comment by antoninbas** [comment]
I did not suggest that you pass `--log-console` to `run_switch.sh`, I suggested that you add it "to the switch command" in the script: `sudo $SWITCH_PATH meter.json ... --log-console`.
`run_switch.sh` is just a convenience script which starts the software switch + populate tables using the CLI. If you do not use the script but run the commands yourself in separate terminals, it gives you a better understanding of what's going on and it's easier to troubleshoot issues. To populate the tables using the bmv2 CLI commands included in `commands.txt`, you can just re-use the command from `run_switch.sh`... You can also start the CLI without piping `commands.txt` in, and run the commands yourself one-by-one.

**Comment by antoninbas** [comment]
closing this since no update
