### ISSUE TITLE
Why the SIGGCOMM Tutorials are removed?

### ISSUE THREAD

**Issue by arijeetsat** [p4lang/tutorials#172]

**Comment by jnfoster** [comment]
Since we use Git, everything is in the history. 

You can find the old tutorial materials at this release https://github.com/p4lang/tutorials/releases/tag/pre-p4d2-2018-spring

We decided to compact the structure because many people seem to get confused running old versions of the exercises on newer versions of the software tools. The new structure will be easier for our volunteer team to keep consistent.
