### ISSUE TITLE
question about multicast

### ISSUE THREAD

**Issue by stdoo** [p4lang/tutorials#22]
Want to know how to implement multicast in P4 switch. I have read the p4-spec, and it seems that **clone_egress_pkt_to_egress** can be used, but not recommended. However there's no use case for that action, and I'm confused about the two arguments(clone_spec, field_list) it takes. How to determine the egress specification with clone_spec ?

**Comment by Wasdns** [comment]
Hi!

As far as I know, this repo has multiple examples in [examples](https://github.com/p4lang/tutorials/tree/master/examples) and samples that showed in SIGCOMM 2016 and 2015. I recommend you to follow the solutions that offered by Barefoot. Learning by Doing.

The runtime commands that enabled multicast features can be found in the bmv2 target `l2switch` on [l2_switch/commands.txt](https://github.com/p4lang/behavioral-model/blob/master/targets/l2_switch/commands.txt). The commands created multicast group 1 at the first: `mc_mgrp_create 1` and created muticast nodes based on the host number, then associate muticast nodes to the group. 

The meta action `clone_egress_pkt_to_egress()` is similar to the action [clone_ingress_pkt_to_egress()](https://github.com/p4lang/tutorials/blob/master/examples/copy_to_cpu/p4src/copy_to_cpu.p4#L76) used in the example named `copy_to_cpu`. These meta actions are used to copy the packet in the pipeline. You can try this example and get more informations from the [README](https://github.com/p4lang/tutorials/tree/master/examples/copy_to_cpu#copy-to-cpu) in `copy_to_cpu`.

Sincerely do I hope that my words is helpful.

**Comment by vgurevich** [comment]
Hello,

clone_* primitives are not really intended to do multicast (see P4 spec
v1.0.3, Section 14 "Recirculation and Cloning" on page 62). Instead,
multicast replication is assumed to be done by a specialized engine that
sits between the ingress and egress pipelines. In the specification it is
referred to as "Queueing Mechanism" and as the spec says on page 2 "The
Queuing Mechanism processes this Egress Specification, generates the
necessary instances of the packet and submits each to the Egress Pipeline."

It turns out that the name "Queueing Mechanism" is somewhat misleading for
the multicast case, since replication has nothing to do with queueing,
except that it is also done between ingress and egress pipeline :) BMv2
uses the term "PRE", which stands for "Packet Replication Engine", and it
makes much more sense. The "real" chips use vendor-specific terminology,
such as MMU, TM (Traffic Manager) or (my personal favorite) PQRS (Packet
Queueing, Replication and Scheduling).

The way PRE works in BMv2-SimpleSwitch is somewhat different from P4 v1.0.3
spec: it uses two distinct fields: standard_metadata.egress_spec and
intrinsic_metadata.mcast_grp to decide where to send the packet. It looks
as follows:

if (intrinsic_metadata.mcast_grp != 0) {
    send_to_multicast_group(intrinsic_metadata.mcast_grp);
else {
    send_to_port(standard_metadata.egress_spec);
}

So, the right thing to do in your program in the ingress pipeline is to
simply choose a multicast group, based, say, on the IP address. You can do
it by modifying the table output_port in your program, like so:

action set_output_mcg(mcast_group) {
    modify_field(intrinsic_metadata.mcast_grp, mcast_group);
}

table ip_forward {
    reads {
        ipv4.dstAddr: exact;
    }
    actions {
        set_output_mcg;
    _drop;
    }
    size : 16384;
}

What is a multicast group? In the most simple sense, it is a set of
destinations. that take the form of pairs (rid, egress_port), where
egress_port is a port the packet must egress from and "rid" is a
"replication ID", which is a unique identifier that can be used to perform
packet modifications. Suppose a multicast group #1 contains the following
nodes: { (1, 1), (2, 1), (2, 2), (3, 1), (3, 4) }. If a packet enters the
ingress pipeline and is sent to the multicast group #1, the egress pipeline
will see 5 separate packets (in some, undefined order) that will have the
fields intrinsic_metadata.egress_rid and standard_metadata.egress_port set
as follows:

   - intrinsic_medata.egress_rid=1  standard_metadata.egress_port=1
   - intrinsic_medata.egress_rid=2  standard_metadata.egress_port=1
   - intrinsic_medata.egress_rid=2  standard_metadata.egress_port=2
   - intrinsic_medata.egress_rid=3  standard_metadata.egress_port=1
   - intrinsic_medata.egress_rid=3  standard_metadata.egress_port=4

Now, you can add another table in your egress() control flow function to
take advantage of the replication ID like so:

action do_nat(dst_ip) {
      modify_field(ipv4.dstAddr,dst_ip);
      add_to_field(ipv4.ttl, -1);
}

table nat_table {
    reads {
        intrinsic_metadata.egress_rid : exact;

    }
    actions {
        do_nat;
        _drop;
    }
    size : 16384;
}

and associate new destination addresses (e..g. 239.2.2.2 -- 239.4.4.4) with
egress_rid values 1, 2 and 3 correspondingly. Then you will see the
following:

   - On port 1 you will see packets with dstAddr 239.2.2.2, 239.3.3.3 and
   239.4.4.4
   - On port 2 you will see a packet with dstAddr 239.3.3.3
   - On port 3 you will see no packets
   - On port 4 you will see a packet with dstAddr 239.4.4.4

Note, that the exact behavior of PRE is not defined in P4 beyond what I
mentioned. The programming is specific to the target, in this case
BMv2-simple_switch, though it is quite representative of many other
systems.

You can see a full example, done by Thomas Edwards here:
https://github.com/FOXNEOAdvancedTechnology/mc_nat_P4

Happy hacking,
Vladimir

**Comment by Wasdns** [comment]
@vgurevich Thank you very much! Your reply is very helpful with my work. 👍

**Comment by stdoo** [comment]
@Wasdns @vgurevich 
Thanks for your help. But I don't understand the commands.
**mc_node_create 1 1
mc_node_create 2 2
mc_node_create 3 3
mc_mgrp_create 1
mc_node_associate 1 0
mc_node_associate 1 1
mc_node_associate 1 2**

I know the **mc_mgrp_create 1** means to create a multicast group #1. But what's **mc_node_create 1 1** and **mc_node_associate 1 0** means? Why create a mc_ node need two arguments, like (1 1).
-------------------------------------------------------------------------------------------------
My guess is that the first arg for mc_node_create is rid, and the second is egree_port. While the first arg for mc_node_associate is group number, but I'm confused about the second arg.

**Comment by vgurevich** [comment]
Hello,

The first three commands create multicast nodes with IDs 0, 1 and 2
correspondingly (assuming you execute them on a clean system).  The first
argument is the replication ID followed by one or more space-separated
ports. The nodes simply exist on their own.

The next command creates multicast group #1, but it has no nodes in it.

The last three commands associate (add) the nodes, created earlier with the
multicast group. The first argument is the multicast group ID and the
second argument is the node id.

Hope, this helps.

Happy hacking,
Vladimir

**Comment by stdoo** [comment]
@vgurevich Very helpful! Thanks very much.

**Comment by jnfoster** [comment]
By the way, the name of that widget should totally be SPQR (Scheduling Packets for Queuing and Replication) right?

**Comment by vgurevich** [comment]
Hello Nate,

At least in all the architectures I am familiar with scheduling comes at
the end. Think of the schedulers as the engines that pull packets out of
the queues (e.g. at a certain rate or following other, more complex
scheduling disciplines) and pass them for egress processing.

Thanks,
Vladimir

**Comment by cc10512** [comment]
It was a pun: SPQR ~= speaker.

**Comment by jafingerhut** [comment]
Darn, I was hoping it was a reference to "Senatus Populusque Romanus" - "The Senate and the Roman people".

Technically I think the PRE widget only does replication, no scheduling, so Packet Replication Engine is pretty accurate, if not very exciting a name.

**Comment by cc10512** [comment]
Enabling a Roman Senate-like legacy would be quite a feat :)

**Comment by vgurevich** [comment]
The competition for the best name is still open, so please, continue to
submit the proposals :)

Here are some comments on the existing situation

   1. In the existing BMv2 targets PRE does everything, although in the
   current implementation it is 95% replication. There is a little modeling of
   queueing and no special modeling of schedulers, but nevertheless *from
   the interface point of view* it is everything. In other words it accepts
   queueing metadata on its input and passes queueing-related metadata on the
   output. That was the basis for my initial comment that the term "PRE" is
   somewhat misleading.
   2. Generally speaking, queueing and replication are not fully
   independent and depending on the queueing architecture, replication can
   happen before or after queuing and sometimes even in the middle. The reason
   for that is that multicast packets can sit in the queue much longer than
   unicast ones (because they need to go to multiple ports). Also, in the
   systems with VOQ (Virtual Output Queueing) design, one needs to know the
   egress port number to queue a packet and this happens only after
   replication (or the packet has to sit in a separate queue). However, at the
   API level, they separate quite well, so once we get to define the control
   plane APIs for these components in PSA, this is something to consider.

Thanks,
Vladimir

**Comment by jnfoster** [comment]
Andy nailed it :-)

-N

**Comment by mohammedelazzab** [comment]
Can egress_port be modified in the egress pipeline ?

**Comment by jnfoster** [comment]
This repository contains the source code for the VM and exercises in the P4 tutorial. It's not the best place to ask general P4 programming questions.

You will probably get a faster answer if you ask on the p4-dev email list or the P4 Slack.

**Comment by mohammedelazzab** [comment]
My question is related to multicast, which is discussed in this thread. The packet replicas in the egress pipeline have the standard_metadata.egress_port set by multicast engine. on Barefoot devices it is not permitted to modify the egress_port of the replica, I just wanted to know if it is the same behavior with the bmv2.

**Comment by antoninbas** [comment]
This is documented in the [simple_switch bmv2 specification](https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md).

**Comment by jnfoster** [comment]
Sure, but I do want to discourage people from asking questions on this repository that are not issues in the tutorial code. Slack and the mailing lists are good places to ask such questions.
