### ISSUE TITLE
Basic_tunnel run issue

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/tutorials#239]
When running this tutorial,this is the error message I'm getting.Any help?
![screenshot from 2019-02-26 10-59-11](https://user-images.githubusercontent.com/44960997/53411356-2e028f80-39be-11e9-9d1e-9e8a6b89a2fb.png)
![screenshot from 2019-02-26 10-59-36](https://user-images.githubusercontent.com/44960997/53411359-3064e980-39be-11e9-97fe-d3a9036a1ff4.png)
![screenshot from 2019-02-26 10-59-58](https://user-images.githubusercontent.com/44960997/53411367-32c74380-39be-11e9-86c7-2b26d851ae44.png)

**Comment by jnfoster** [comment]
Does your P4 program have a table named "myTunnel_exact"? It looks like P4 Runtime is looking for such a table, but it doesn't exist.

**Comment by jnfoster** [comment]
Also, I recommend typing in code using Markdown not uploading screenshots. Screenshots are clunky (e.g., you had to split yours across three images) and also makes it harder for people who might want to help you. In particular they can't cut and paste to replicate or diagnose your bug.

More generally, I find these [suggestions](http://www.cs.cornell.edu/courses/cs3110/2019sp/thoughtful.html) on asking technical questions helpful.

**Comment by Juniortheone** [comment]
I searched on this issue and it seems the Readme file needs to be changed. I did this using the new file by @mlda065  but it still did not work.

**Comment by jnfoster** [comment]
Running `make run` is not expected to work until step 1 of the exercise, as described in detail in the [README.md](https://github.com/p4lang/tutorials/blob/master/exercises/basic_tunnel/README.md) file has been completed. In particular, Step 1 Part 5 says:

> TODO: Define a new table called myTunnel_exact that perfoms an exact match on the dst_id field of the myTunnel header. This table should invoke either the myTunnel_forward action if the there is a match in the table and it should invoke the drop action otherwise.

Until you do this step, some of the commands specified in the `sX-runtime.json` files will fail because certain tables do not exist. The error message provided `Attribute Error: could not find 'MyIngress.myTunnel_exact...` and the hints in step 2 of the Troubleshooting section of the README.md file make this clear.

If you want to run the code without doing it, copy the files from `basic_tunnel/solution` on top of the corresponding files in `basic_tunnel` and it will run flawlessly.

**Comment by Juniortheone** [comment]
@jnfoster Thanks
