### ISSUE TITLE
Virtual Machine freezes PC

### ISSUE THREAD

**Issue by annafianto** [p4lang/tutorials#281]
I've followed the instruction. As soon as I run "vagrant up" which initiates the virtual machine, it freezes my PC completely, I have to physically force the PC to restart or shut down, otherwise PC won't response to any button that I pushed. Is there any particular configuration for this, in the virtual machine maybe?

**Comment by jnfoster** [comment]
What happens if you import a pre-packaged VM image rather than trying to creating one from scratch? The VM we just prepared for SIGCOMM '19 is available [here](http://stanford.edu/~sibanez/docs/).  

If your machine crashes even when using a pre-packaged VM, then the issue is with your OS, BIOS, or Virtualbox install, not our scripts. If it works for you, maybe you don't need to build at all?
