### ISSUE TITLE
no GUI after machine reboots 

### ISSUE THREAD

**Issue by reveurrafc** [p4lang/tutorials#282]
After vagrant up , login with p4 and  issuing the command sudo shutdown -r now
 there is no gui .I'm able to run vagarnt init as well as up and in cli it shows machine booted and ready

**Comment by jafingerhut** [comment]
Closing quite old issue.  I personally use the install steps documented in this repo every month, and have not come across this issue.  Granted, I don't use a wide variety of base OS's in my testing, so that may be the root cause.  Hopefully someone will raise this again and it can be debugged if someone has the time and interest to help.
