### ISSUE TITLE
runtime writecounter

### ISSUE THREAD

**Issue by Fengww2014** [p4lang/tutorials#307]
i've known there is a function to read counter in `/utils/p4runtime_lib/switch.py /`:

![image](https://user-images.githubusercontent.com/30151004/69021161-e4495180-09f1-11ea-9197-8a038f28ca84.png)

but I'm wondering to know how can i writer to the counter or register like this.

**Comment by jafingerhut** [comment]
I do not have any tested working Python code to give to you, but the P4Runtime API does define that it is possible to write counter values from the controller to the switch.  At the very least, you need to change ReadRequest to WriteRequest, and probably do some kind of `Write(request)` call instead of `Read(request)` as shown in the code you give in your comment.  You would also need to have a parameter that provides the desired count value to write into the counter, and include that in the message somehow.
