### ISSUE TITLE
I use "p4c -b bmv2 mycode.p4" to compile my code, but keyword "reject" is not supported.

### ISSUE THREAD

**Issue by HEMINSAN** [p4lang/tutorials#308]
when I used "reject" in parse section, I got "[–Wwarn=unsupported] warning: Explicit transition to reject not supported on this target".

**Comment by jafingerhut** [comment]
That is expected behavior for using p4c to compile a program that does `#include "v1model.p4"`, i.e. is using the v1model architecture.

If you want the parser to record an error during parsing, in such a way that later when the packet is executing its ingress control, you can distinguish packets that got a parsing error from ones that did not, you could instead of trying to transition to the `reject` state, instead transition to a new state you define, something like this one:
```
state parserErrorFoo {
    verify(false, error.Foo);
    transition reject;
}
```
Replace `error.Foo` with whatever error value you want to use, either one of the predefined ones, or one you define yourself.

The `transition` statement will never be executed, because `verify` with a condition of `false` will always record a parser error and terminate packet parsing.  If you do not want the warning message from the compiler, you could use `transition accept;` there instead -- it will never be executed, so it does not matter much.

Regardless of whether parsing terminates with no error, or an error, the packet will always start its ingress control execution shortly afterwards.  You can write P4 code there that checks the value of standard_metadata.parser_error, and either compare it to whatever error value you want, or if the only thing that matters for your P4 program is to distinguish packets that got an error during parsing from ones that did not, you could write code like:
```
if (standard_metadata.parser_error != error.NoError) {
    mark_to_drop(standard_metadata);
    exit;
}
// rest of packet processing goes here
```
That example would be what you want if you want to drop all packets that got an error during parsing, but you can react to parser errors differently, if you write the code to do so.

**Comment by jafingerhut** [comment]
@antoninbas @mbudiu-vmw Any idea why this warning message appears when one transitions to the reject state and target bmv2?  As far as I know, the only difference between transitioning to accept and transitioning to reject is that in a sub-parser, transitioning to reject means that the entire top-level parser terminates immediately, similar to an `exit` statement in a control.  The spec says nothing about how accept vs. reject is handled other than that, so unless p4c doesn't handle the sub-parser reject when flattening the code, it should be handled just fine, by otherwise treating it the same as accept?

**Comment by mbudiu-vmw** [comment]
The BMv2 parser language does not support either 'accept' or 'reject'. 'accept' is implicit in the transition to a control (ingress).

**Comment by HEMINSAN** [comment]
thanks all you guys!
I also found an explanation in "https://github.com/p4lang/behavioral-model/blob/971732f48570f848a27a8f54b25b7447732d8591/docs/simple_switch.md", in "Restrictions on parser code" section.
