### ISSUE TITLE
Error while compiling any exercise

### ISSUE THREAD

**Issue by sanaa50** [p4lang/tutorials#310]
Hi,
I'm trying to run the provided exercises in this repository, but all of them failed. This is the output of running `make` of the basic example:
```
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
P4 switch s1 did not start correctly.
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1
```
and this is the log of the switch:
```
Calling target program-options parser
[10:31:30.744] [bmv2] [D] [thread 21934] Set default default entry for table 'MyIngress.ipv4_lpm': MyIngress.drop - 
I1119 10:31:30.811098797   21934 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Server listening on 0.0.0.0:50051
[10:31:30.878] [bmv2] [E] [thread 21934] Error by sr_module_change_subscribe for 'openconfig-interfaces': Requested schema model is not known
```

How to solve the issue ?

**Comment by maxsmith303030** [comment]
I'm new to p4 myself so I don't know if this will be helpful but, from the error it shows it's the p4 switch `s1`. If I'm right, that's the switch which acts as the grpc server and from your error script, it was using the `simple_switch_grpc` argument. That should mean the grpc server failed to execute. One of the suggestions from the `readme` files on troubleshooting this is to `make stop` and trying `make run` again. However, you are saying "any exercise" failed to run which seems strange because I created mine recently and everything works fine. It might have something to do with your environment. Why don't you try creating everything using the prebuilt `.ovf` file which you can just import. That works perfectly.

**Comment by antoninbas** [comment]
I don't think it's possible to get this error if you used the tutorials VM. You would need to build bmv2 simple_switch_grpc yourself and run configure with `--with-sysrepo`.
