### ISSUE TITLE
Help running with multi switch

### ISSUE THREAD

**Issue by maxsmith303030** [p4lang/tutorials#313]
I am new to P4 and I want to create a network with multiple p4 switches.  I have read extensively on the readme files in the tutorials and other materials. I have seen a similar question earlier asked on how to create networks, but I am a bit lost. The `multi_switch_mininet.py` file in the mininet directory seems meant exactly for this purpose. Going through the script, it has several arguments, but I don't see the argument asking for the number of switches to be added. However, there's a `--json` argument where upon further reading, one can specify the topology needed there. I tried doing that using `bmv2`(I have installed that as well) following the instructions in the `bmv2` repository but, it failed. It makes sense to me for it to fail to execute because the `multi_switch.mininet.py` file as it name suggests is supposed to create multiple switches, and without specifying how many switches should be created, it should fail.  Any help on that? Also,  there's something that I can't seem to get a hang on; on compiling a `.p4` file, it generates a `.json` file which is different from the `json` file that describes the network topology. How are these two `json` files integrated?

**Comment by jafingerhut** [comment]
If you follow the instructions in this part of the README, it takes 1 to 2 hours with a reliable Internet connection throughout, on a host machine where you have VirtualBox installed, and 25 Gbytes of free disk space, but that will install all of the P4 open source tools: the p4c compiler, the behavioral-model simple_switch process, mininet, and several other things, necessary to run the existing example tutorial exercises, which use mininet.

JSON is a syntax for a data file format, usually with "dictionaries" of key/value pairs, but also numbers, lists, etc.  Many, many different kinds of data are stored in JSON files throughout the world.  They differ in what keys are significant/important, and what the type of values associated with those keys are.  So the fact that something is JSON format only tells you the syntax, not what keys/values to use, which you need to find documented elsewhere.

Mininet uses JSON syntax to represent topologies, p4c uses JSON syntax to represent compiled P4 programs.  Except for the fact that both use JSON syntax, their contents are completely unrelated.

**Comment by maxsmith303030** [comment]
Thank you. If by README, do you mean the readme file in the p4 tutorial directory because that is what I used? The one with the polar bear as the desktop background after installation or a different readme file? I am a bit familiar with json but, thank you for your clarification. I'm aware that they're different json files with different key/value pairs as you indicated. In my initial question I wanted to know how they are integrated with the bmv2 switch(simple_switch_grpc). I'm trying to create my network using the p4 tutorials as a guide. From the readme in bmv2, when running the command to set up a network incorporating mininet, it calls for one json argument which I presume is the json file of the compiled `.p4` file. However, when you make run the p4 runtime example, it has two json arguments as shown below:
`sudo python ../../utils/run_exercise.py -t topology.json -j build/advanced_tunnel.json -b simple_switch_grpc`. The `topology.json` file is for the network topology while the `advanced_tunnel.json` is for the compiled `.p4` file.  I tried that in setting up my network but it failed. I was wondering where I went wrong.

**Comment by maxsmith303030** [comment]
I know it's quite simple to do that because I have emulated that by modifying the tutorial files but, I want to know the fundamentals of it. I read the `guide`, and it was constructive but, when running with the bmv2, it doesn't work( I mean when I try to re-create) it. Apparently, I am missing something. I'm just an intermediary programmer and new to this SDN concept so, I'm sorry if my question is trivial.

**Comment by jafingerhut** [comment]
`topology.json` is a JSON file with the 'schema' (i.e. the keys/type-of-values expected to be found there) defined completely by a Python program in the tutorials repository, probably `run_exercise.py`.  Whether those are documented in English somewhere, I do not know.  It might be the only way it is "documented" is by reading and understanding the relevant part of the Python source code in the tutorials repository.

The `build/advanced_tunnel.json` in your example command line is most likely the output of the p4c compiler, from compiling a P4 source file `advanced_tunnel.p4`.

I would recommend never hand-editing the JSON output files from the `p4c` compiler, although nothing will stop you from doing so if you really wish to.

The topology.json file is meant to be hand-edited, but again, I do not know if what is legal vs. what is not considered legal is documented in English anywhere.  Sometimes open source projects end up in the "Use the source, Luke" kind of mindset, because writing documentation and keeping it up to date with code can be time consuming.

**Comment by maxsmith303030** [comment]
Thank you.
