### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zanshuo** [p4lang/tutorials#317]
![image](https://user-images.githubusercontent.com/47976773/70377725-c1f08700-1952-11ea-9b77-c2e90a596040.png)

how to solve the problem?

**Comment by jafingerhut** [comment]
You have not given us many clues to go on, but at least a few.  For example, how did you install P4 open source tools before you reached this point?  Did you follow the instructions in the p4lang/tutorials README to create a new Linux VM using the `vagrant up` command?  Did you download a pre-built VM from somewhere?  Something else?

I suspect the answer is "something else", because it appears that you do not have the auto-generated Python wrapper modules for the P4Runtime API installed, from the error message "No module named v1" just after the line saying it was trying to import "from p4.v1 import p4runtime_pb2".

Consider creating a new Linux VM following the instructions in the tutorials README here: https://github.com/p4lang/tutorials#obtaining-required-software

If you have done that, then I do not understand why you are getting the error message you did.

**Comment by zanshuo** [comment]
Actually, I run them on a Ubantu 18.04 machine,and when I input vargran up command as README write,it failes because of some errors,so I have to install P4 open source tools with instructions in https://p4.org/p4/getting-started-with-p4.html.

**Comment by jafingerhut** [comment]
I have tested `vagrant up` without problem on my system recently, so if you are getting errors, it might be useful to know what errors you encountered, in case there is a problem that can be fixed there.

In addition to using `vagrant up` to create a VM, you could also download a pre-built VM that was used in an August 2019 tutorial at SIGCOMM here: https://github.com/p4lang/tutorials/tree/sigcomm19

**Comment by jafingerhut** [comment]
In particular, note the part of the README that says you should have 25 GBytes of free disk space on the host machine before running `vagrant up`.  If you run out of disk space on the host machine, all kinds of weird things can go wrong.

**Comment by jnfoster** [comment]
Closing this for lack of discussion...
