### ISSUE TITLE
https://github.com/p4lang/tutorials/p4runtime compile Error

### ISSUE THREAD

**Issue by johnhauhnar** [p4lang/tutorials#319]
I followed the instructions here https://github.com/p4lang/tutorials/blob/master/README.md
I'm able to run all the examples without any compile errors with the exception of p4runtime example..

Below is what I got during compilation., any suggestion?
_

> p4@p4:~/jj/tutorials/exercises/p4runtime$ make
> mkdir -p build pcaps logs
> sudo python ../../utils/run_exercise.py -t topology.json -j build/ -b simple_switch_grpc
> Reading topology file.
> Building mininet topology.
> Invalid JSON file: build/
> ../../utils/Makefile:35: recipe for target 'run' failed
> make: *** [run] Error 1
> p4@p4:~/jj/tutorials/exercises/p4runtime$

_

**Comment by jafingerhut** [comment]
I have a system with the latest master version of this tutorials repository, and p4c-bm2-ss, simple_switch_grpc, etc. commands all compiled and installed.

When I change to the directory `exercises/p4runtime`, with no changes to any files in this tutorials repository at all, and enter the command `make`, I see this:

```
$ make
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/advanced_tunnel.p4.p4info.txt -o build/advanced_tunnel.json advanced_tunnel.p4
sudo python ../../utils/run_exercise.py -t topology.json -j build/advanced_tunnel.json -b simple_switch_grpc
Reading topology file.
Building mininet topology.
s1 -> gRPC port: 50051
s2 -> gRPC port: 50052
s3 -> gRPC port: 50053
**********
h1
default interface: eth0	10.0.1.1	08:00:00:00:01:11
**********
**********
h2
default interface: eth0	10.0.2.2	08:00:00:00:02:22
**********
**********
h3
default interface: eth0	10.0.3.3	08:00:00:00:03:33
**********
Starting mininet CLI

======================================================================
Welcome to the BMV2 Mininet CLI!
======================================================================
Your P4 program is installed into the BMV2 software switch
and your initial runtime configuration is loaded. You can interact
with the network using the mininet CLI below.

To inspect or change the switch configuration, connect to
its CLI from your host operating system using this command:
  simple_switch_CLI --thrift-port <switch thrift port>

To view a switch log, run this command from your host OS:
  tail -f /home/andy/tutorials/master/exercises/p4runtime/logs/<switchname>.log

To view the switch output pcap, check the pcap files in /home/andy/tutorials/master/exercises/p4runtime/pcaps:
 for example run:  sudo tcpdump -xxx -r s1-eth1.pcap

To view the P4Runtime requests sent to the switch, check the
corresponding txt file in /home/andy/tutorials/master/exercises/p4runtime/logs:
 for example run:  cat /home/andy/tutorials/master/exercises/p4runtime/logs/s1-p4runtime-requests.txt

mininet> 
```

Your output shows no `p4c-bm2-ss` command, and in the line with `run_exercise.py`, my output shows `build/advanced_tunnel.json` where yours shows only `build/`, and later your output has an error message `Invalid JSON file: build/`, probably because `build/` is just the name of a directory, not a JSON file.

Does your system contain a P4 program named `advanced_tunnel.p4` in the directory `exercises/p4runtime`?

Have you made changes to it, or does it still have its original contents copied from this repository?

If I type the command `which p4c-bm2-ss`, I see:
```
$ which p4c-bm2-ss
/usr/local/bin/p4c-bm2-ss
```
What do you see as output of that command on your system?

**Comment by johnhauhnar** [comment]
Thanks for the quick response...
After seeing your compile output which differs significantly from mine, I was convinced that something was messed up.. as I actually tried few stuffs mentioned here "https://github.com/p4lang/PI/blob/master/README.md".
I re-created the VM from the scratch and the problem is no more seen..
I'm now able to run the p4runtime example without compile errors.
