### ISSUE TITLE
Client-Server example

### ISSUE THREAD

**Issue by SanaaComp** [p4lang/tutorials#331]
Is there any P4 client-server example?
I tried to write a simple code for that purpose, but I can not make it work.

I appreciate any help.

**Comment by jafingerhut** [comment]
Depending upon what you are looking for, the calculator example is a very simple kind of 'server' implemented in P4, where the requests from clients are single packets containing requests to perform calculations, and the responses are single packets containing the answers.

In general, writing a P4 program to take single packets, and give back single packet responses, where what you want to manipulate is in a sequence of fixed-length headers at the beginning of the packet, looks like that example.

If you want an HTTP server written in P4, realize that terminating a TCP connection is a very very stateful activity, and implementations in C e.g. in the Linux kernel use a lot of data structures, loops, etc. that P4 does not have, by design.  Someone may have written P4 code to terminate a TCP connection, but if they have, I would bet it either has severe limitations in what TCP features it supports, or it was very challenging to write, and challenging to read and understand, or all of those things are true about it.  I also would not be surprised if no one has had the patience to try doing so, after seeing the difficulties involved.

What are you looking for?

**Comment by jafingerhut** [comment]
Here is a link to the calculator example I mentioned in my previous comment: https://github.com/p4lang/tutorials/tree/master/exercises/calc

**Comment by SanaaComp** [comment]
> Depending upon what you are looking for, the calculator example is a very simple kind of 'server' implemented in P4, where the requests from clients are single packets containing requests to perform calculations, and the responses are single packets containing the answers.
> 
> In general, writing a P4 program to take single packets, and give back single packet responses, where what you want to manipulate is in a sequence of fixed-length headers at the beginning of the packet, looks like that example.
> 
> If you want an HTTP server written in P4, realize that terminating a TCP connection is a very very stateful activity, and implementations in C e.g. in the Linux kernel use a lot of data structures, loops, etc. that P4 does not have, by design. Someone may have written P4 code to terminate a TCP connection, but if they have, I would bet it either has severe limitations in what TCP features it supports, or it was very challenging to write, and challenging to read and understand, or all of those things are true about it. I also would not be surprised if no one has had the patience to try doing so, after seeing the difficulties involved.
> 
> What are you looking for?
 
I have a simple network of three host (h1, h2 and h3) and one switch (s1). Both of h2 and h3 act as UDP servers.
h1 can issue a request to one of the servers by using 11.1.1.1  IP address (which is a virtual IP address). After that, h2 or h3 responses to that request.
The response from the servers to h1 is my problem. The requests are being directed to the servers, but h1 receives no response.

**Comment by jafingerhut** [comment]
In these tutorials, the switches run your P4 program.  The hosts run whatever general purpose language programs you want, typically Python programs that send and receive packets (or they can also open TCP connections, because the hosts have full Linux kernel TCP/IP implementations in them, unlike the switches running P4 code).

What you describe in the previous comment is not the switch acting as a client or server, but forwarding packets between hosts.  If a host is sending a packet that you expect to get to another host, but it isn't, something is stopping that, but what the root cause is, is not clear without further debugging.  Are you familiar with the simple_switch log files written into a logs directory by most or all of these tutorials?  Have you read them before?  Do you understand at least some of their contents?

That I consider an _essential_ skill for debugging (a) whether a switch is receiving a packet at all, and (b) what the P4 code does while processing the packet, e.g. what table search keys does it search for, what matching entries did it find, if any?  Or did it get a miss?  What action was executed?  Was the packet eventually dropped, or sent out of a port?  The answers to all of those questions can be learned by reading that log file.  Ignore it at your frustration.  Yes, it can be frustrating to learn to interpret its contents, but it is more frustrating to ignore it, in my opinion.

**Comment by SanaaComp** [comment]
I read the log file. My packets are being transmitted from h1 out of one of s1 ports (let's say port 2). Then there is no response coming from port 2.
Is it okay to show some of my code here?

**Comment by jafingerhut** [comment]
Before posting any code, think about this question: Is the s1 port number 2 where a packet is going out attached to a host in your Mininet topology?

If yes, suppose we call that host h4, just to give it a name.

Question: What device is responsible for sending a response to the packet sent to host h4?

Answer: The host h4.

Question: Is there any P4 code running on host h4?

Answer: No.  P4 code is only running on the emulated switches in a Mininet topology created by this tutorials repository, not on the hosts.

Question: What code is responsible for receiving packets on a host, and sending replies?

Answer: Whatever programs you choose to run on those hosts.  Several of the tutorials have small Python programs like send.py or receive.py that are run on the hosts for doing this.

Question: If I want a host to receive packets, and send replies to them, is there a Python program example that already does this?

Answer: I do not know.  Perhaps someone else does.

**Comment by jafingerhut** [comment]
Another question, that may or may not be a question you have, but I'll post it anyway.

Question: What if I want the emulated switch s1 to send a response packet back to the sender, without sending it to host h4 at all?

Answer: Then you should write P4 code running on switch s1 that _does not send a packet to h4_, but instead modifies the received packet into the response that should be sent back to the sender, and send it out a port that leads back to the sender.  If the goal is not to bother h4, then don't bother h4.

**Comment by SanaaComp** [comment]
You are assuming my UDP server is h4. I'm running `iperf -s -u` in h4 and `iperf -c 11.1.1.1 -u` in my host (h1).
My server (h4) receives nothing from h1. But s1.log shows that there is a stream of packets being carried out of port 1 where h1 is attached ,and this stream is being directed to port 2 where h4 is attached. There should be a response  from h4 on port 2, but nothing is being received on port 2.

**Comment by jafingerhut** [comment]
I am not assuming anything.   My comment began with these words "Is the s1 port number 2 where a packet is going out attached to a host in your Mininet topology?

If yes, suppose we call that host h4, just to give it a name."

I didn't say anything about the "If no" case, because I can't predict your topology from what you have said so far.

Here is a general rule for you to internalize: If a switch's port is attached to a host, and no packets are being received by the switch on that port, then it is because (a) the host is not sending packets on that link, or (b) the link is somehow non-functional.   (b) seems unlikely, and you can check it by doing a ping from that host and see if it gets to the switch.  If it is (a), then the fix is "run different programs on that host that send packets, under the conditions you want it to send packets".

**Comment by SanaaComp** [comment]
The problem was solved by adding 
`update_checksum_with_payload(true, { hdr.ipv4.srcAddr, hdr.ipv4.dstAddr, 8w0, hdr.ipv4.protocol, hdr.udp.length_, hdr.udp.srcPort, hdr.udp.dstPort,  hdr.udp.length_}, hdr.udp.checksum, HashAlgorithm.csum16);`
