### ISSUE TITLE
table stuff in p4 is confusing to me 

### ISSUE THREAD

**Issue by mdayyaz** [p4lang/tutorials#341]
please explain with this example : 
 table ipv4_match {
        key = {
            hdr.ipv4.dst_addr: lpm;
        }
        actions = {
            drop_action;
            to_port_action;
        }
        size = 1024;
        default_action = drop_action;
    }

based on key hdr.ipv4.dst_addr for longest prefix match it has two possible actions 
drop_action 
to_port_action 
which action function will be executed on what match  ?  
is it one after another if longest prefix match is found then what happens which action will be executed

**Comment by jafingerhut** [comment]
One call to `ipv4_match.apply()` will cause exactly one action to execute, always.

If the value of the key `hdr.ipv4.dst_addr` matches no table entries (typically installed via a control plane API, but you can also define table entries in the source code via `const entries`, but that is not in your example), then that is a miss.

On a miss, the table's default action is executed.  When your example program is loaded, the initial value of the default action for table `ipv4_match` is `drop_action`, but the control plane is allowed to change it to `to_port_action` if it wishes.  You can put a `const` keyword before `default_action =` to prevent that possibility.

(In a table with no `default_action` defined in the source code, it defaults to an action named `NoAction` that does nothing.)

If the search key matches only one entry in the table, that entry is the "winner" and its corresponding action is executed, which could be either drop_action or to_port_action, but no others.  The control plane decides which entries have which corresponding action, when it installs the table entries.

If the search key matches multiple table entries, because the match_kind is `lpm`, only the one with the longest prefix is the "winner", and only its corresponding action is executed.

**Comment by mdayyaz** [comment]
thank you very much for reply . 
please clarify one more thing. 
table ipv4_match {
key = {
hdr.ipv4.dst_addr: lpm;
}
actions = {
drop_action;
to_port_action;
}
size = 1024;
default_action = drop_action;
}
in this example its not very clear which action to be executed in which case (hit or miss) , just list is specified ,  as per your last comment when table.apply()  "will cause exactly one action to execute, always." which is that ? and on what basis ? and how it decide which action to execute , as their is no selector to specify clearly   which action it will it execute? its not very clear by looking at code. 

can u point me to some video for p4 for dummy ? which shows involvement of P4 program and journey of packet considering P4 packet , switch and control plane or may u can explain me with example .

**Comment by jafingerhut** [comment]
I would suspect there is a tutorial in video form that makes this clear, but I have not watched any very recently to confirm which one to recommend.

In the absence of a 'const entries' declaration in a table, which your example table does not have, when the P4 program is first loaded into a device, the table contains no entries at all.  In that situation, every time a packet is processed, it will always miss, and execute the default action.

Your example code does not give a definition for to_port_action, but suppose it looks like this:

action to_port_action(bit<9> output_port) {
    standard_metadata.egress_spec = output_port;
}

Now suppose some control plane software makes an appropriate function call that causes a table entry to be added with these contents:

hdr.ipv4.dst_addr 10.1.0.0/16. (i.e. the first 16 bits must be exactly 10.1, the remaining 16 bits can be anything), action=to_port_action, parameter output_port=7

If that succeeds, then the table will have one entry in it.

If a packet is then processed that has a field value with ipv4.dst_addr=10.2.3.4, that address does not match the one table entry, so the result is a miss, and the default action will be executed.

If a packet is processed that has a field value with ipv4.dst_addr=10.1.3.4, that address does match the one table entry, so the result is a hit.  The action corresponding to that address is to_port_action, called with a parameter value of output_port=7.  Note that the parameter value is supplied by the control plane code when the table entry was added.

If the control plane software now adds another table entry like this:

hdr.ipv4.dst_addr 10.1.3.0/24. (i.e. the first 24 bits must be exactly 10.1.3, the remaining 8 bits can be anything), action=drop_action (I will assume here that drop_action has no parameters, so the control plane software does not need to supply any parameter values when adding the table entry).

If that succeeds, now there are two table entries in the table.

If another packet arrives in this new state with ipv4.dst_addr=10.1.3.4, it matches both of the table entries, but only one will be the winner.  For match_kind lpm in the P4 source code, the rule is that among all entries that match the packet field(s), the one with the longest prefix will "win".  In this case, that is the entry with key 10.1.3.0/24, so when the table is applied, the action associated with that entry will be executed, which is drop_action.
