### ISSUE TITLE
Load_balancing issue

### ISSUE THREAD

**Issue by Hoangttrieu** [p4lang/tutorials#348]
Hello,
I'm learning the P4 load balancing in the tutorial, but when i execute the code incomplete (the first step of the tutorial), the packages are sent normally. Do you have some ideas where the problem come from?
Thanks

**Comment by jafingerhut** [comment]
It appears that for the load_balance exercise, the README claims that packets will be dropped with the original code, and outlines the changes you need to enable it to forward packets.

The README and the code do not match up, though, since the original code before your changes CAN forward packets, just without the desired hash function used for doing the load balancing over available paths.

The program and README have been substantially similar since 2018, which is as far back as I looked in the commit history, so I do not know whether it has always had this mismatch between README and starting code.

**Comment by jafingerhut** [comment]
The starter P4 code for this exercise and the README have both been updated recently in PR #622, which should resolve this issue.
