### ISSUE TITLE
Question about "egress_global_timestamp" in the link_monitor

### ISSUE THREAD

**Issue by ls760008979** [p4lang/tutorials#371]
Why the field "egress_global_timestamp" between different switch seems out of order， what i mean is why is the "egress_global_timestamp" of  former switch larger than the latter one as show below.
![cur-t](https://user-images.githubusercontent.com/30166591/84595715-07ef5000-ae8c-11ea-8bb2-d84badcae4a3.png)

**Comment by jafingerhut** [comment]
As of the latest version of BMv2 simple_switch, all timestamps start at 0 _when the simple_switch process starts_.  It seems unlikely that one would be able to synchronize the start of simple_switch processes as tightly as 1 microsecond apart, which is the unit of that timestamp field.

I should probably add notes somewhere one time documenting this fact, and what can be done about it if one wished these timestamps to be more closely synchronized between multiple simple_switch processes, because yours is at least the third question in the last 2 weeks asking about it.

**Comment by jafingerhut** [comment]
Here is a new section I have created a pull request on the p4lang/behavioral-model repository to answer questions about time stamp synchronization in BMv2 simple_switch.  Read it over and see if it addresses your question: https://github.com/jafingerhut/behavioral-model/blob/add-notes-on-timestamp-synchronization/docs/simple_switch.md#BMv2-timestamp-implementation-notes

**Comment by ls760008979** [comment]
> Here is a new section I have created a pull request on the p4lang/behavioral-model repository to answer questions about time stamp synchronization in BMv2 simple_switch. Read it over and see if it addresses your question: https://github.com/jafingerhut/behavioral-model/blob/add-notes-on-timestamp-synchronization/docs/simple_switch.md#BMv2-timestamp-implementation-notes

Okay,thanks.
