### ISSUE TITLE
Any alternatives to BMV2 switch for research purposes

### ISSUE THREAD

**Issue by sbibek** [p4lang/tutorials#384]
I am a student trying to get started into research into using p4. I am currently using the BMV2 reference switch but I need more precise results and more metadata than what the simple switch can offer right now. Any suggestions on this front?

**Comment by jafingerhut** [comment]
It might help to know what kind of precise results you are looking for, and what kind of metadata you do not have that you wish for.

**Comment by sbibek** [comment]
The simple_switch is much slower and I am not sure that the hop and link latency information I am calculating are precise or not. 
For example, I followed the MRI tutorial to calculate the hop latency and also I was able to calculate the link latency (ingress time of s2 - egress time of s1). To calculate the link latency, I had to change the source where each switch will just take the timestamp of the system rather than starting from 0 as it was suggested in the documentation. I am trying to see if the results are good or not with the following simple topo.

h0--------(s1)-----------(s2)-----h1

I have sent the UDP proble packet from h0 to h1 each 100ms and h1 receives them and prints them. The following is what I am seeing.
1. Without any traffic between h0 and h1, the hop latency is stable around 30-50 microseconds most of the time and the link latency between switch 1 and 2 is about 700-800 microseconds most of the time.
2. Now I generate iperf traffic between the h0 and h1 (TCP which sends at rate of ~20Mbit/s). Now the hop latency drops to ab
out 5-15 microseconds and the link latency drops to about 150-250 microseconds with occasional large spikes in both the metric. 

I am not sure but I was expecting the metrics to rise instead in the above case. Am I doing anything wrong in here?

Also regarding the metadata, I am trying to calculate the link usage but I see there is no counter information in the v1model. Is there any other way to approach this?

**Comment by jafingerhut** [comment]
If your goal is to simulate what would happen in an actual network of hosts and switches, and get latency measurements like would occur in that situation, then the two most likely things I would suggest are:

(a) get a real network of hosts and switches like the ones you want to do performance tests on, and run them there.  This can be expensive, and time consuming, and painstaking, I know, but the results will be real.  If you can borrow such a lab setup, rather than build one yourself, that can save a lot of money.  If you can find someone that has done similar performance experiments on the setup before you, and is willing to coach you through it, that can help save time.

(b) simulate a network like that, using a simulation setup that goes to some effort to have performance similar to a real network.  There are a few listed here https://en.wikipedia.org/wiki/Network_simulation such as OPNET and NS2/NS3.

bmv2 can give you accurate behavior in terms of packets out relative to packets in given a particular P4 program, but besides the reasons listed here that it is not necessarily good for high performance packet forwarding: https://github.com/p4lang/behavioral-model/blob/master/docs/performance.md there are other things that I have not investigated carefully, but can likely lead to surprises in latency and throughput measurements:

(1) bmv2 is a user space process, and a multi-host and multi-switch network emulated using mininet has all of the latency of system calls that are monitoring virtual ethernet links, which I do not know how predictable those are.  Do they poll the virtual ethernet interfaces every so many microseconds for new packets?  Do they make a blocking read call and then are waken up by the operating system mechanisms for finishing a blocking read, and if so, what is the latency variation possible in that operating system mechanism?  When packets are sent by bmv2 across a virtual ethernet, are they buffered in some operating system write buffer for a while before they actually go into the virtual ethernet interface?

(2) I have done some measurements some time ago that if you try to in mininet create a link with a megabit/second maximum rate.R, it behaves more like a FIFO queue of packets that can have packets appended to it much faster than rate R, but packets are dequeued from it and sent to the other end of the virtual ethernet interface at rate R megabits per second.  A real physical Ethernet link with rate R between two switches does not behave like that -- it does not contain a FIFO queue of packets inside of it that can receive packets much faster than rate R.

**Comment by sbibek** [comment]
1. So I should move away from mininet and try with NS2/NS3, OPNET simulation systems right? 

2. Regarding the bmv2, I am interested in calculating the link usage but I didn't find anything in metadata that helps me to do so. Am I missing something here? 

3. I was trying to correlate the queue depth (standard_metadata.deq_qdepth) with the link congestion. But when I tried to saturate the capacity of the switch with flooded UDP using iperf, most of the packets gets dropped but still the `deq_qdepth` doesn't increase significantly. Is this expected behavior? I was expecting the queue depth to increase here. 

Thanks

**Comment by jafingerhut** [comment]
1. It depends on what you are trying to do.  If you are trying to do at least semi-accurate performance simulations of a system of switches and hosts (i.e. accurately model link bandwidths, latencies, etc.), it is entirely possible that someone, somewhere knows how to use Mininet to do that.  Given what I have seen so far, I would be fairly surprised if that is possible.  It seems well suited to testing packet-in, packet-out behavior, and control plane code interacting with the switches, but as far as I can see, performance simulation is not its strength.

2. You can write P4 code that maintains packet and byte counts of packets received on each link, and/or packets sent on each link, and read those periodically from control plane software that you write.  There should also be such statistics maintained by the operating system for the veth interfaces created for connecting hosts and switches to each other, which you should be able to look at via commands link "ifconfig".  You would need to do that periodically to get an idea of how the rate of packet/byte transmission is changing in different time intervals.  bmv2 has no built-in functionality to show you "this link is used at 80%".  Even if it did have such a thing, it wouldn't make much sense to try to use it on virtual Ethernet interfaces, because they have no fixed bit rate built into them -- they are software constructs that by default go as fast as the operating system and host CPU cores can make them go.

3. See my previous comment where I mention that when you use mininet to configure some links with a particular megabit/second capacity, that they link does NOT behave like a physical constant bit rate link does.  Instead, it behaves like a FIFO queue of packets, which the sender can put packets into as fast as software lets it do so, and then packets are drained from that FIFO queue at the configured link rate.  In my experience, physical network links running at a constant bit rate of 1 Megabit per second do not let you send packets to them faster than 1 Megabit per second.  veth's configured by Mininet do let you do that, so whatever device (e.g a bmv2 switch) sending packets to them will not build up a queue internally, instead sending packets to the link as fast as veth software and your system's CPU's let it.

**Comment by sbibek** [comment]
I tried to confirm the behavior and yes the FIFO-like behavior actually would create an issue as you said. Upon querying, I was said that the queueing would be a problem if we push to the data rate of the mininet which are usually in MBPS. But here in our case, we are seeing just shy of 10 Mbps which they claim shouldn't have caused any such issue. I tried checking the bandwidth without P4 and yes the link capacity is higher than 10 MBPS. In this case, the P4 switch should have shown an increase in queue utilization right?

**Comment by antoninbas** [comment]
To create congestion inside bmv2, instead of at the links, you need to make sure you configure egress rates correctly, e.g. using the `set_queue_rate` CLI command. The rate you choose need to be less than the rate of the links and the rate of the links should be less than what bmv2 can process for your P4 program.

Do make sure you build bmv2 using these flags: https://github.com/p4lang/behavioral-model/blob/master/docs/performance.md#which-build-flags-to-use
