### ISSUE TITLE
ImportError: No module named p4.v1

### ISSUE THREAD

**Issue by goish135** [p4lang/tutorials#388]
I want to run p4 on Ubuntu (not in VM)
This is my install steps:
step1: git clone https://github.com/jafingerhut/p4-guide
step2: ./p4-guide/bin/install-p4dev.sh

and test by 
- cd p4c/build
- make check

When  I run tutorial/exercise/basic 's basic.p4 but i got error  
$ make run  
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
sudo python ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  File "/home/sundar/p4lang/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
  File "/home/sundar/p4lang/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  File "/home/sundar/p4lang/tutorials/utils/p4runtime_lib/switch.py", line 20, in <module>
    from p4.v1 import p4runtime_pb2
ImportError: No module named p4.v1
../../utils/Makefile:35: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by jnfoster** [comment]
This sounds like an issue with the jafingerhut/p4guide install scripts, not the tutorial exercises. In particular, if you read the error message, it shows that the Python library for controlling switches via P4Runtime has not been properly installed. 

Please ask your question on that repository?

**Comment by jnfoster** [comment]
Also, curious that your home directory is named `sundar` which is pretty different than your user name here. Are you really starting from a clean Ubuntu install or an existing VM?

**Comment by jafingerhut** [comment]
Another odd thing is that the script named in the original issue does not install _anything_, at least since I made a change to it in Nov 2019 because I consider that one so old as to be obsolete.  It only prints some messages recommending using a different install script and exits.  So unless they intentionally got an old copy of my p4-guide repository from about 1 year ago or longer, the script they named will not install anything.

**Comment by LeoWII** [comment]
How can i properly install the python library. I have the same problem but i couldn't fix it.

**Comment by sadmankiba** [comment]
Installing `p4runtime` package works, but it requires `python >= 3.6`. 
```
pip3 install p4runtime
```

**Comment by DavidAraujo98** [comment]
Even after installing p4rutime with pip it is unable to find the module, ideas ?

**Comment by jafingerhut** [comment]
@sadmankiba @DavidAruajo98 It is not clear from your messages _exactly_ what you did before you saw the errors that you saw.  In general, errors such as these often depend on the full sequence of installation steps that you took on the system since you started from a freshly installed, unmodified Linux system.

If you follow the instructions in the top level README of this repository in the "Obtaining required software" section here: https://github.com/p4lang/tutorials#obtaining-required-software then I test those steps every month, and they end up with a system that runs the basic exercise code just fine.

If you deviate from those steps in any way, even one that seems insignificantly small to you, that may be the root cause of the reason why your system gives an error, but my testing did not.

**Comment by jafingerhut** [comment]
Update to my previous comment: When I say I test the instructions in that section of the README, I mean I test the part of those instructions that explain how to run `vagrant up`.  I DO NOT test the last paragraph of that section where it suggests running Bash scripts on an Ubuntu 16.04 system.  Those parts of the instructions refer to Bash scripts that do not exist, and I am going to submit a PR soon to remove that last paragraph of that section, as those instructions will not work as written, and are potentially confusing.

**Comment by rst0git** [comment]
> Even after installing p4rutime with pip it is unable to find the module, ideas ?

In addition to Andy's comments, I just wanted to add that some of the python modules are provides by [PI](https://github.com/p4lang/PI).

**Comment by joshuachough** [comment]
For me, I was getting this error because I forgot to `source p4setup.bash`, as stated in @jafingerhut 's [`README-install-troubleshooting.md`](https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md#quick-instructions-for-successful-install-script-run):

> Note 1: If you use install-p4dev-v7.sh and use bash as your command shell (the default on Ubuntu and Fedora Linux), you should execute the command source p4setup.bash in every bash shell where you wish to run the P4 development tools. You can add the source p4setup.bash line to your $HOME/.bashrc file, so that it will automatically be run for you in any new bash shell you create.
