### ISSUE TITLE
P4 broadcasting rules

### ISSUE THREAD

**Issue by ThiagoBuen** [p4lang/tutorials#398]
Hi,

I am currently working with a P4 switch for a master's thesis project. In our scope, we applied the multicast behavior rules to the bmv2's packet replication engine, setting the required metadata and the needed values in the ingress pipeline up with the CLI commands (mc_mgrp_create, mc_node_create, and mc_node_association).

For a scenario that has only 1 switch, the multicast behavior handles our project's assumptions splendidly. However, as we expand for more switches in the network topology, the packet flow becomes chaotic. This is due to a packet backflow between the switches when the multicast happens. 

A solution that comes to my mind would be creating a filter that prevents the replication engine from sending the received packet at the same ingress port. Is there a way to do this or another solution to solve this issue?

Best regards,

![NetworkTopologyExample](https://user-images.githubusercontent.com/42388965/103691871-b0264c80-4f75-11eb-9f08-d45f2975a1b2.png)

**Comment by antoninbas** [comment]
One easy way to do it with bmv2 is to drop the packet in egress if the egress port matches the ingress port (https://github.com/antoninbas/p4runtime-go-client/blob/master/cmd/l2_switch/l2_switch.p4#L38). This typically means that you are "wasting" bandwidth as packets dropped in egress are still accounted for and you can end up under-utilizing the egress link. But that's generally not a concern with bmv2.

Another way is to create a different multicast group for each ingress port, with each group excluding that ingress port specifically. That may require a large number of groups (for broadcast, you will need N groups, where N is the number of ports for your switch, instead of a single group).

Targets other than bmv2 may have a more natural way to configure their packet replication engine to avoid replicating a packet to the ingress port.

**Comment by ThiagoBuen** [comment]
Thank you for your support, Antonin!

I am going to focus on what you highlighted.
