### ISSUE TITLE
How can the switch actively send data to the controller after matching the action

### ISSUE THREAD

**Issue by whalexiao** [p4lang/tutorials#410]
I am new to P4 and need switch actively send data to the controller after the switch matches the action. What should I do? Thanks！

**Comment by jfingerh** [comment]
Many P4 devices have a "CPU port", and if you are using the P4Runtime API protocol between the controller and the switch, messages sent from the switch to its CPU port are turned into"PacketIn" P4Runtime messages to the controller.

Similarly, "PacketOut" messages from the controller to the switch are injected into the switch so that they can be processed by the P4 program, appearing as if they arrived on the CPU port as the input port of the packet.

The `simple_switch_grpc` software switch supports this.  A short example program and a PTF test that exercises this is published here: https://github.com/jafingerhut/p4-guide/tree/master/ptf-tests/packetinout

**Comment by whalexiao** [comment]
> Many P4 devices have a "CPU port", and if you are using the P4Runtime API protocol between the controller and the switch, messages sent from the switch to its CPU port are turned into"PacketIn" P4Runtime messages to the controller.
> 
> Similarly, "PacketOut" messages from the controller to the switch are injected into the switch so that they can be processed by the P4 program, appearing as if they arrived on the CPU port as the input port of the packet.
> 
> The `simple_switch_grpc` software switch supports this. A short example program and a PTF test that exercises this is published here: https://github.com/jafingerhut/p4-guide/tree/master/ptf-tests/packetinout
Thank you for your prompt reply！！
