### ISSUE TITLE
I can't file the tutorial files in The VM image /usr/local/share/p4c/p4include/v1model.p4 Not Found

### ISSUE THREAD

**Issue by inshalayaz** [p4lang/tutorials#411]
The VM doesn't have the modules.
/usr/local/share/p4c/p4include/v1model.p4
the share directory doesn't have p4c folder

**Comment by inshalayaz** [comment]
![Uploading p4.JPG…]()

**Comment by jafingerhut** [comment]
"The VM" you mention could have been created by you in any of a hundred different ways, or you might have downloaded a tutorials VM from any of half a dozen different sites I am aware of, and probably many more.

It would help if you described precisely what you did to get at the VM you have.  e.g. did you download this repository?  What commit SHA is the latest one you got and used?  Did you run `vagrant up` in some directory?  Which one?  Which operating system is running on the machine where you tried this?  What version of vagrant and VirtualBox did you install there before running `vagrant up`?  How much free disk space was available on that system before you ran `vagrant up`?  Is there still sgnificant free disk space when you finished, or is your disk full now, and likely the run failed because you overflowed your disk capacity?  Did you save the logs of that run and look for any error messages?

**Comment by inshalayaz** [comment]
I ran vagrant up. I have a lot of space remaning. I downloaded the virtual machine on Windows 10 and ran a vagrant up that installed an Ubuntu Virtual machine for me.

**Comment by inshalayaz** [comment]
I cloned the it from this repo the original one.

**Comment by jafingerhut** [comment]
I have not done that on a Windows host system before, but I have on a macOS host machine with plenty of disk space available, and it often works.  I won't say it works 100% of the time, because things can go wrong, e.g. if your Internet connection is too slow, or disconnects completely for too long, then downloads of various software packages can fail.  I'd recommend making sure your system has a good reliable Internet connection, and save the output of `vagrant up` in a file so you can look through it for problems if things go badly the next time.

**Comment by inshalayaz** [comment]
The problem is resolved thanks :)
