### ISSUE TITLE
Can the p4 language create new data packets in the process of pipline

### ISSUE THREAD

**Issue by whalexiao** [p4lang/tutorials#415]
I want to create a new packet to carry some information when certain conditions are matched. (If it is not a clone operation, what should I do)

**Comment by jafingerhut** [comment]
P4 the language, when executing a P4 parser or control, is pretty fundamentally "one packet plus metadata in, one packet plus metadata out".  All dropping, cloning, multicast replication, etc. happens "outside" of parsers and controls in the architecture.

What event is it that triggers the creation of a new packet that you want to send?  If it is the receiving of a packet, you can use a clone operation, and use the option to truncate the cloned packet's payload so that it does not contain the original packet's payload, and then replace the headers with whatever new packet you want to send.

**Comment by jnfoster** [comment]
Let me encourage you to move this discussion over to forum.p4.org!

**Comment by whalexiao** [comment]
Thanks, your answer is very helpful!
