### ISSUE TITLE
issues building the vm

### ISSUE THREAD

**Issue by gcbourdon** [p4lang/tutorials#419]
After I install vagrant and have virtual box v 6.1, I run the vagrant up command in the tutorials/vm folder and the vm loads up but only has the vagrant login (password: vagrant). Also, when logged in, there is neither user or root bootstrap.sh. Do I need to have an older version of virtual box? I tried dropping both files from my windows 10 host with bi-directional clipboard but wouldn't work.

**Comment by jfingerh** [comment]
One thing to check would be whether the host system has enough free disk space before you started the `vagrant up` command (I think 15 GBytes might be enough, but not sure as I have never tried it with that little free disk space, always more).  Another is that you have a good solid reliable Internet connection for the entire duration that `vagrant up` is running.  It downloads 1 to 2 GBytes of data at different parts of the installation throughout, not only at the beginning.

If you are interested in trying a pre-built VM, or a different installation script, see here: https://forum.p4.org/t/installing-open-source-p4-development-tools/84

**Comment by whaleyhua** [comment]
Exactly the same issue for me. I don't see a user called p4 in the VM I got from "vagrant up". Only vagrant where there is no tutorials. I have enough disk space and I have good internet connection, by the way.

**Comment by jfingerh** [comment]
@whaleyhua I recommend to you the same link as in my previous comment for some alternatives that may give better results for you: https://forum.p4.org/t/installing-open-source-p4-development-tools/84

**Comment by hahada5** [comment]
@jfingerh  Hello, thanks for your help. I downloaded the last version image you provided and used Virtual box to open it. But it just stop in black screen without GUI. I have modified the setting of display, RAM and so on, but doesn't help. Did you encounter this problem before? Thanks for your help again.

**Comment by jafingerhut** [comment]
@hahada5 I just tried downloading an Ubuntu 20.04 VM image that I built using VirtualBox on a Mac system, and loading it onto VirtualBox running on a Windows 10 system, and got a similar problematic behavior that you describe -- just stop at a black screen with no GUI.  I do not know why that is, but am open to suggestions from anyone with more experience at creating and using VM images in VirtualBox.  The pre-built image I tried this with is the 2019-09-07 version on this page: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

Note: If you are willing to create a new Ubuntu 20.04 VM, and run the install-p4dev-v4.sh script mentioned on that same page I just linked, it can take 1-2 hours to run, but it works in my monthly tests.

**Comment by jafingerhut** [comment]
@hahada5 I have removed the image dated 2021-Sep-07 from the web page linked below, and added one dated 2021-Sep-12.  The only difference is that I ran `vagrant up` in the vm-ubuntu-20.04 directory on a Windows 10 system with Vagrant and VirtualBox installed, instead of on a macOS host as I have done in the past.  The image created I was able to import and boot up on VirtualBox on a Windows 10 host machine, and also on my macOS system.  See if it works for you?

As a fallback, if you install VirtualBox and Vagrant on your system, you should be able to get the _latest_ version as of today (2021-Sep-13) of this p4lang/tutorials repository, change to the vm-ubuntu-20.04 directory, run `vagrant up`, and if you have enough disk space and reliable Internet connection for the next couple of hours, should have a VM with all P4 open source dev tools compiled and working on it.

**Comment by hahada5** [comment]
@jafingerhut  Thank you a lot. I'll try the latest image afterwards. BTW, with your guide I created a new image with ubuntu-20.04 os , cloned tutorial github and cloned your guide (https://github.com/jafingerhut/p4-guide), then run ./install-p4dev-v4.sh. Now I build the environment successfully. TKS!

**Comment by jafingerhut** [comment]
Closing this issue as it seems that at least some of the problems were addressed.  If you still have issues specific to installing the tutorials VM, feel free to create another issue.
