### ISSUE TITLE
Unable to make run, no module named mininet.net

### ISSUE THREAD

**Issue by kartikx** [p4lang/tutorials#420]
## Background
Hi everyone, I have been trying to build the `exercises/basic` code, but haven't been able to do so. I am trying to configure my own machine (not VM), since I plan on developing further using P4.
Output of `lsb_release -a`:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
I am aware of the issues related to this version of Ubuntu, and hence was working on @jafingerhut 's branch [here](https://github.com/jafingerhut/tutorials/tree/add-2021-mar-vm-based-on-ubuntu-20.04). I have been able to use the VM image associated with this branch to run the exercises, but I would prefer not developing on a VM.

## Problem Description
When running `make run` in `exercises/basic`, I get:
```
[~/basic]$ make run
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter dstAddr
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                  ^^^^^^^
basic.p4(81): [--Wwarn=unused] warning: Unused action parameter port
    action ipv4_forward(macAddr_t dstAddr, egressSpec_t port) {
                                                        ^^^^
sudo python3 ../../utils/run_exercise.py -t pod-topo/topology.json -j build/basic.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 25, in <module>
    from p4_mininet import P4Switch, P4Host
  File "/home/kartik/Desktop/tutorials-add-2021-mar-vm-based-on-ubuntu-20.04/utils/p4_mininet.py", line 16, in <module>
    from mininet.net import Mininet
ModuleNotFoundError: No module named 'mininet.net'
make: *** [../../utils/Makefile:35: run] Error 1
```

I had installed mininet from the Ubuntu packages, as mentioned in the third heading on the [Mininet download page](http://mininet.org/download/). Mininet is installed:
```
[~/basic]$ mn --version
2.3.0.dev6
```

Furthermore, importing Mininet on an example python file works fine (with python3, python2 and python invocations):
```
from mininet.net import Mininet

def main():
    print("Hello World!");

if __name__ == "__main__":
    main()
```

## Possible Sources of Error
1. I have not compiled Mininet from source. The `user-bootstrap.sh` script however does compile from source.
2. I have not run `user-bootstrap.sh` and `root-bootstrap.sh`, since I had already built dev tools like `p4c`, `bmv2` from source. I am afraid that running the script now could break my existing installation.

I would really appreciate any insight into this problem. Thanks in advance!

**Comment by jafingerhut** [comment]
I wish I knew what to suggest that is a smaller sequence of steps than my suggestion below, but I do not know, and I have no idea how many hours it might take me to find out.

I have spent many hours tweaking bash installation scripts that I test about once per month to see if they continue to work, and pass a simple set of tests.  I always test those scripts starting from an unmodified Ubuntu 16.04, 18.04, or 20.04 Linux installation, precisely because there can be interactions between install methods and what order those steps are performed in, and I really do not know all of the files that each of the installation steps might modify.  I consider myself fortunate if I can find _one_ order of commands that leaves a freshly installed Ubuntu system in a final state that passes those tests.

That is also the reason why I like using freshly installed VMs, because that is so much quicker than reinstalling Ubuntu on the bare machine, and if I ever appear to have messed up the state of such a VM, as long as I copy the few files of mine that I have been editing somewhere else, I can be confident that I can start over by deleting that VM, and create a brand new one, and run the install scripts.  Yes, it can take a while to run the scripts, but it is only a few manual steps to do it, and all of the experimentation to figure out how to make them work has already been done.
