### ISSUE TITLE
I can't run make command 

### ISSUE THREAD

**Issue by LeoWII** [p4lang/tutorials#424]
from p4.v1 import p4runtime_pb2
ImportError: No module named p4.v1
make: *** [../../utils/Makefile:35: run] Error 1

I'm learning the p4 language. And i couldn't solve this problem. If anyone knows the problem i need help.

**Comment by jafingerhut** [comment]
I am not sure how you installed the P4 open source development tools.  Perhaps they have not been installed correctly on the system you are using, and that is the reason for this failure.

If you are interested in a tested way of installing the P4 development tools on an Ubuntu Linux system, or downloading a virtual machine with the tools pre-installed for you, see here: https://forum.p4.org/t/installing-open-source-p4-development-tools/84

**Comment by LeoWII** [comment]
I just find out the problem is my ubuntu is not updating repository. bootstrap.sh files on p4lang/tutorials don't work properly bc of it. I tried on Ubuntu 16.04 its working normal. But on my Ubuntu 20.04 i still couldn't manage to make it run.

**Comment by jfingerh** [comment]
The scripts in the master branch have not been tested on anything but Ubuntu 16.04, so unsurprising if they fail on Ubuntu 20.04.

I have a branch in my fork of this repository that has a vm-ubuntu-20.04 directory in it with working install scripts for Ubuntu 20.04.  I have not done extensive testing of every tutorials example to verify that _everything_ works, but the basic tutorial definitely builds and pings.

```bash
git clone https://github.com/jafingerhut/tutorials
cd tutorials
git checkout add-2021-mar-vm-based-on-ubuntu-20.04
cd vm-ubuntu-20.04
```

**Comment by rst0git** [comment]
@jfingerh Do you know why https://github.com/p4lang/tutorials/pull/403 has not been merged yet?

**Comment by jfingerh** [comment]
@rst0git Probably because an early comment I first created it warned that it was still experimental, and not thoroughly tested.  If you think your improvements and testing have improved on that situation, I'd suggest adding a comment there and pinging someone like Nate Foster to see if he wants to review it, or suggest someone else to review it.  Note that merging it with all of the Python3 changes will mean that the Ubuntu 16.04 VM creation steps will work, but the tutorials will not run unless someone updates the Ubuntu 16.04 VM creation steps to fully install all of the Python3 parts needed.   Given that free long-term support for Ubuntu 16.04 has been over for a while now, I think it would be reasonable if p4lang/tutorials no longer attempted to support Ubuntu 16.04.
