### ISSUE TITLE
cannot execute vagrant up sucessfully

### ISSUE THREAD

**Issue by 529669517** [p4lang/tutorials#431]
When I try to execute "vagrant up"

it issues an error
![1633693093(1)](https://user-images.githubusercontent.com/45109782/136550599-f84bb103-867e-48f0-ae7e-09a515290663.png)

    p4-tutorial: E: The repository 'https://download.sublimetext.com apt/stable/ Release' does not have a Release file.
The SSH command responded with a non-zero exit status. 
Vagrant assumes that this means the command failed. 
The output for this command should be in the log above. 
Please read the output to determine what went wrong.

**Comment by jfingerh** [comment]
The root-bootstrap.sh script uses commands copied from the instructions on the Sublime Text web page for installing Sublime Text.   In my monthly testing of these install scripts for the last year or so, these commands have always succeeded, until a couple of weeks ago the last time I tested them.  I checked the instructions on Sublime's web site, and they have not changed, so they are either having issues with their web servers, or they haven't yet updated their install instructions.

The smallest change you can make that should help you get past that issue is to delete the line `sublime-text \` in the list of packages for the `apt-get install ...` command in the file `root-bootstrap.sh`.

If the problem with installing `sublime-text` continues for very long, we can consider merging in a change that no longer attempts to install it.

**Comment by jafingerhut** [comment]
With change #432 the latest scripts no longer attempt to install the Sublime text editor, avoiding this problem.
