### ISSUE TITLE
link_monitor issue

### ISSUE THREAD

**Issue by dianjingshilezhi** [p4lang/tutorials#449]
when i run the code,
i did't get cur_time and last_time ,all of them is 0.

**Comment by jfingerh** [comment]
I would recommend asking your question on https://forum.p4.org  since then others with a similar question will be more likely to find the question and its answer, vs. a probably-closed Github issue.

Whether you follow up on that web site, or here, please be much more specific about (a) what commands you ran, (b) which program you were running, e.g. if it is exactly the same as a published one, give a link to the entire program, (c) tell what you saw that you did not expect, and (d) explain what behavior you were hoping to see, but did not.

That makes it far easier for people to give you specific advice related to your issue.  Without those details, anyone trying to answer your question has too little information to go on.
