### ISSUE TITLE
ModuleNotFoundError: No module named 'p4.config'

### ISSUE THREAD

**Issue by MojtabaTaj** [p4lang/tutorials#560]
I was trying to make the basic files but i faced this problem . can you help me to solve it ?

**Comment by AdarshRawat1** [comment]
If the issue persists, then share, which method of installation you have used. [ There are multiple ways  ]
If you want to know more about selecting the right method for your device [ Setup ] then you can read [Installation troubleshooting Guide.](install-troubleshooting)

**Comment by MojtabaTaj** [comment]
> Follow [ Obtaining required software instructions](https://github.com/p4lang/tutorials#obtaining-required-software) and you should be good to go.
> 
> Do let us know if the issue persists after following the guide. PS -_Similar issues were faced before by other users_

Thanks for your reply. I have installed ubuntu 22.04 . 
for P4 programming i installed bvmv, p4c, mininet and python3 . 
but when i tried to run basic tutorial, i saw this error .

**Comment by AdarshRawat1** [comment]
>  I have installed ubuntu 22.04 . for P4 programming i installed bvmv, p4c, mininet and python3 . but when i tried to run basic tutorial, i saw this error .

I think you need to follow [Quick instructions for successful install script run](https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md#quick-instructions-for-successful-install-script-run) Guide.

**Comment by AdarshRawat1** [comment]
@MojtabaTaj were you able to debug your issue ?

**Comment by MojtabaTaj** [comment]
> @MojtabaTaj were you able to debug your issue ?

no . the issue is still standing . do you have idea how to solve the issue ?

**Comment by MojtabaTaj** [comment]
as i can see the problem stems from p4runtime_lib / Simple_controller/ from p4.config.v1 import p4info_pb2 / line code 22

**Comment by jafingerhut** [comment]
There are only a few ways to install the open source P4 development tools so that they all work together to run these tutorials.  There are thousands of variations on those that do not quite work.

If you have used one of the two methods described on this page https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
then those are some of the few ways I have personally tested to work.

If you have used _any other way_ to install open source P4 development tools, then I do not think that I have time to spend helping you debug your setup.  Maybe someone else might, but they would need to know a lot of details about exactly how your system was installed.
