### ISSUE TITLE
Is there any p4lang environment for macbook m2?

### ISSUE THREAD

**Issue by ROBINRUGAN** [p4lang/tutorials#571]
I found that on the MacBook with M1 and M2 chip series, it's impossible to install VirtualBox and its images, which seems to be specifically prepared for x86 users. However, this poses a significant challenge for learners on arm64. @antoninbas @jafingerhut

**Comment by jafingerhut** [comment]
Note that as far as I know, VirtualBox is not supported on arm64-based Macs.  I am happy to learn differently if someone knows otherwise.  If it is not supported, then we would need to use some other virtualization software, perhaps with vagrant or something else.  If you know what works, please share.

I have successfully installed the open source P4 development tools on an arm64-based Mac using these steps:

+ Install UTM virtualization software: https://mac.getutm.app/
+ Create an Ubuntu 20.04 Linux VM in UTM
+ Clone the p4-guide repository: https://github.com/jafingerhut/p4-guide
+ Follow the instructions here for running the install-p4dev-v7.sh install script: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md#quick-instructions-for-successful-install-script-run

After that succeeded, I was able to follow the instructions in this tutorials repo to run the exercises.

**Comment by ROBINRUGAN** [comment]
thank you so much! I will try it now. If there exists some problems I will contact with you~

**Comment by ROBINRUGAN** [comment]
I successfully installed them, and everything went well. Thank you again for your timely guidance.
