### ISSUE TITLE
Problems in installing bmv2 and p4c on kali Linux 

### ISSUE THREAD

**Issue by Bryan-Ndum** [p4lang/tutorials#618]
When I follow all the steps I keep having errors from;

Installation Problems: Difficulty installing p4c and bmv2 due to missing dependencies and repository errors.

Missing Dependencies: Encountered errors related to missing Thrift and Protobuf libraries during the build process.

Build Errors: Encountered specific build errors related to linking and Boost library requirements.
Repository Issues: Issues with repositories, including a 404 error for the p4lang repository, hindering dependency installation.

Final Build Failure: Despite resolving some dependencies, final build processes still failed, leading to frustration.

**Comment by jafingerhut** [comment]
The steps that suggest using `vagrant up` or `vagrant up dev` always use Ubuntu Linux, so I guess you are not trying to use those parts of the instructions.

I have never tried installing this software on Kali Linux personally, and do not know the differences between Kali and Ubuntu distributions.  If someone else reading this is interested in helping you to do that, great, but I doubt I will have time to try experienting with it myself to see what works and what doesn't on another Linux distribution.

I would recommend that you might have better success in trying to use instructions that build the P4 development tools from source code, rather than the ones that try to install precompiled binaries, which have only been tested on Ubuntu Linux, e.g. avoid any commands like `sudo apt-get install p4lang-bmv2`.

**Comment by Brytimz** [comment]
Thank you Sir, I will change to Ubuntu Linux to make it work.

**Comment by jafingerhut** [comment]
Closing this issue as there are no plans to support Kali Linux in the instructions or scripts in this repository, and the Ubuntu Linux instructions and scripts are tested every month, and working.
