### ISSUE TITLE
Nonexistent log file in source_routing

### ISSUE THREAD

**Issue by liujed** [p4lang/tutorials#94]
The end of Step 1 in [`P4D2_2017_Fall/exercises/source_routing/README.md`](../blob/master/P4D2_2017_Fall/exercises/source_routing/README.md) refers to a `build/logs/s1.log`, but this file does not exist, even after running the example program.

**Comment by jafingerhut** [comment]
Hopefully this issue was fixed long ago, but adding "help wanted" label in hopes someone might verify that.

**Comment by stano45** [comment]
@jafingerhut The log files are generated as expected on latest main. Also, the [README](https://github.com/p4lang/tutorials/blob/ee16fbde2a4c69ae66220a8112625b1b1559d61d/exercises/source_routing/README.md#step-1-run-the-incomplete-starter-code) now correctly points to `logs/s1.log`  instead of `build/logs/s1.log` (see step 1, point 6).

**Comment by jafingerhut** [comment]
@stano45 Thanks for checking the details on this.  From your investigation, do you believe that this issue can be closed as fixed?

**Comment by stano45** [comment]
@jafingerhut Yes, based on my testing I believe this is fixed on latest main.

**Comment by jafingerhut** [comment]
Again, thanks for digging through the details on this.  If you are applying for a GSoC 2024 project, please keep track of this issue with a link or something to add to your accomplishments, as the issue becomes trickier to find after it has been closed (not impossible, just a bit more time-consuming, typically).
